name: Deploy project to our server
on:
  push:
    branches:
      - mamon
jobs:
  FTP-Deploy-Softvence:
    name: FTP-Deploy-Softvence
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER_NAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
