name: Deploy project to our server
on:
  push:
    branches:
      - mamon
jobs:
  FTP-Deploy-Softvence:
    name: FTP-Deploy-Softvence
    runs-on: ubuntu-latest
    steps:
      # v2 থেকে v4 এ আপডেট করা হয়েছে
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER_NAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
